#: import asset chordwise.utils.asset

<Header@StackLayout>:
    size_hint_y: None
    height: '70dp'

    Button:
        text: '<'
        size: self.parent.height, self.parent.height
        size_hint: None, None
        on_release: app.history_back()

    Image:
        id: logo
        source: asset('img/chordwise.png')
        size_hint: None, None
        height: self.parent.height
        width: self.texture.width / (self.texture.height / self.parent.height)
